[Unit]
Description=Generate sshd host keys on the data partition
ConditionFirstBoot=
ConditionPathIsReadWrite=
ConditionPathIsSymbolicLink=
ConditionPathIsMountPoint=/data
RequiresMountsFor=/data
After=systemd-tmpfiles-setup.service

[Service]
ExecStart=
ExecStart=/usr/local/sbin/ssh-generate-host-keys
